[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 921600
board_upload.flash_size = 2MB
build_unflags = -std=gnu++11
build_flags =
  -std=gnu17
  -DMUSIC2_PULSE_ENGINE_TICK_US=25
  -DMUSIC2_PLAYBACK_TIMER_ISR_DISPATCH=0
