#pragma once

#include <stdint.h>

#define PROTO_VERSION (3u)
#define PROTO_MIN_COMPAT_VERSION (2u)
#define PROTO_MAGIC (0x4D32u)

#define MOTOR_COUNT (8u)
#define PLAYBACK_MOTOR_COUNT (6u)

#define FEATURE_FLAG_TIMED_STREAMING (0x01u)
#define FEATURE_FLAG_PLAYBACK_EVENT_STREAMING (FEATURE_FLAG_TIMED_STREAMING)
#define FEATURE_FLAG_HOME (0x02u)
#define FEATURE_FLAG_WARMUP (0x04u)
#define FEATURE_FLAG_STEP_MOTION (0x08u)
#define FEATURE_FLAG_DIRECTION_FLIP (0x10u)
#define FEATURE_FLAG_CONTINUOUS_PLAYBACK_ENGINE (0x20u)
#define FEATURE_FLAG_PLAYBACK_SETUP_PROFILE (0x40u)
#define FEATURE_FLAG_SPEECH_ASSIST (0x80u)

#define EXACT_MOTION_FEATURE_DIRECTIONAL_STEP_MOTION (0x01u)

#define SETUP_BASE_PAYLOAD_SIZE (5u)
#define SETUP_PLAYBACK_PROFILE_SIZE (12u)
#define SETUP_SPEECH_ASSIST_SIZE (6u)
#define SETUP_WITH_PLAYBACK_PROFILE_PAYLOAD_SIZE (SETUP_BASE_PAYLOAD_SIZE + SETUP_PLAYBACK_PROFILE_SIZE)
#define SETUP_WITH_SPEECH_ASSIST_PAYLOAD_SIZE (SETUP_WITH_PLAYBACK_PROFILE_PAYLOAD_SIZE + SETUP_SPEECH_ASSIST_SIZE)

#define PROTO_CMD_HELLO (0x01u)
#define PROTO_CMD_SETUP (0x02u)
#define PROTO_CMD_STREAM_BEGIN (0x03u)
#define PROTO_CMD_STREAM_APPEND (0x04u)
#define PROTO_CMD_STREAM_END (0x05u)
#define PROTO_CMD_PLAY (0x06u)
#define PROTO_CMD_STOP (0x07u)
#define PROTO_CMD_STATUS (0x08u)
#define PROTO_CMD_METRICS (0x09u)
#define PROTO_CMD_HOME (0x0Au)
#define PROTO_CMD_WARMUP (0x0Bu)
#define PROTO_CMD_STEP_MOTION (0x0Cu)
#define PROTO_CMD_PLAY_AT (0x0Du)
#define PROTO_CMD_ACK (0x7Eu)
#define PROTO_CMD_ERR (0x7Fu)

#define PROTO_FRAME_HEADER_SIZE (9u)
#define PROTO_FRAME_CRC_SIZE (2u)

#define PROTO_MAX_PAYLOAD (1024u)
#define PROTO_MAX_RAW_FRAME (PROTO_FRAME_HEADER_SIZE + PROTO_MAX_PAYLOAD + PROTO_FRAME_CRC_SIZE)
#define PROTO_MAX_ENCODED_FRAME (PROTO_MAX_RAW_FRAME + (PROTO_MAX_RAW_FRAME / 254u) + 2u)

typedef struct {
  uint8_t version;
  uint8_t cmd;
  uint16_t seq;
  uint8_t flags;
  uint16_t payload_len;
  uint8_t payload[PROTO_MAX_PAYLOAD];
} proto_frame_t;
